# configuration for master branch
# official releases go here
-
  branches:
    only:
      - master

  image: Visual Studio 2017

  version: 0.2.{build}

  build_script:
    - cmd: msbuild src/Sancho.Client.Core/Sancho.Client.Core.csproj /t:restore
    - cmd: msbuild src/Sancho.Client.Core/Sancho.Client.Core.csproj /t:pack /p:Configuration=Release /p:Version="%APPVEYOR_BUILD_VERSION%"

  artifacts:
    - path: '**\Sancho.Client.Core.*.nupkg'

# configuration for develop branch
# new versions go here
-
  branches:
    only:
      - develop
  
  image: Visual Studio 2017

  version: 0.2.{build}-ci
  
  build_script:
    - cmd: msbuild src/Sancho.Client.Core/Sancho.Client.Core.csproj /t:restore
    - cmd: msbuild src/Sancho.Client.Core/Sancho.Client.Core.csproj /t:pack /p:Configuration=Release /p:Version="%APPVEYOR_BUILD_VERSION%"

  artifacts:
    - path: '**\Sancho.Client.Core.*.nupkg'

  deploy:
    provider: NuGet
    api_key:
      secure: LT8bWnUXsN/QwIft5V3jlpmBFz9k5TXXceJ8j42eHYOD79VJ9jaf+qlxq2vy173K
